### DISCUSSION TITLE
Adding a Smart Shunt to the universal R48xx CAN controller

### DISCUSSION THREAD

**Discussion by mjpalmowski** [mjpalmowski/CAN-BUS-control-R4875G1-with-ESPHome-and-MQTT#11] [General]
If you have your R4875G1 connected to your storage battery, and that battery is connected to a consumer while charging, you might be interested in monitoring the outgoing amps to influence your charging amp settings. Alternatively, you may want to maintain the battery's state of charge (SOC) at 50% by setting the charging amps equal to the outgoing amps.

Below is a hardware setup compatible with the ESPHome project. 

[And here is an example YAML with all the latest mod-cons: AC-limit, auto-set-up any R48xx model, dual inverters and smart-SHUNT.](https://github.com/mjpalmowski/CAN-BUS-control-R4875G1-with-ESPHome-and-MQTT/blob/main/2xR48xx_with_SHUNT.YAML)

The code required to add the current value to your ESP32 configuration is straightforward:

(The settings are calibrated for a 75mV/300A shunt. Depending on the orientation of the shunt, export amps are displayed as negative values, while import amps are shown as positive values.)
```
i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true
  id: bus_a

sensor:
  # INA226 Sensor Configuration
  - platform: ina226
    address: 0x40
    i2c_id: bus_a
    shunt_resistance: 0.00025
    max_current: 300
    adc_time: 140us
    adc_averaging: 128
    update_interval: 300ms
    current:
      name: "Shunt Current"
      unit_of_measurement: "A"
      accuracy_decimals: 2
      id: shunt_current
    shunt_voltage:
      name: "Shunt Voltage"
      unit_of_measurement: "V"
      accuracy_decimals: 5

```     

![Screenshot 2025-01-22 120120](https://github.com/user-attachments/assets/ce8d3328-cc0b-4eba-b712-51c6ed04149c)
